FireMonitorPlatform/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'

  root :to => "home#index"

end

FireMonitorPlatform/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.has_role? :admin
      can :manage, :all
    else
      can :read, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

FireMonitorPlatform/app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

FireMonitorPlatform/app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

FireMonitorPlatform/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def after_sign_in_path_for(resource)
    if resource.is_a?(User)
      if User.count==1
        resource.add_role 'admin'
      end
      resource
    end
    root_path
  end
end

FireMonitorPlatform/app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!
  def index
  end
end

FireMonitorPlatform/app/helpers/application_helper.rb
module ApplicationHelper
end

FireMonitorPlatform/app/helpers/home_helper.rb
module HomeHelper
end

FireMonitorPlatform/app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<% if user_signed_in? %>
<p>The User is logged in</p>
<% if can? :manage, :Home %>
<%= link_to "About", home_about_path %>
<% end %>
<% end %>

FireMonitorPlatform/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FireMonitorPlatform</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<% if current_user %>
<%= link_to('quit', destroy_user_session_path, :method =>:delete) %>
    <% link_to('修改密码', edit_registration_path(:user)) %>
    <% else %>
<%= link_to('注册', new_registration_path(:user)) %> |
    <% link_to('登陆', new_session_path(:user)) %>
    <% end %>

<%= yield %>

</body>
</html>